version: "3.5"
services:
    web:
        build: .
        ports:
            - 0.0.0.0:5001:5001
        networks: 
            - potentiometer-network
        labels:
            - "SERVICE_5001_NAME=QuizEngine"
            - "SERVICE_TAGS=QuizEngineTag"
        restart: always
networks:
    potentiometer-network:
        name: potentiometer-network
        external: true