version: "3.5"
services:
    web:
        build: .
        ports:
            - 0.0.0.0:5010:5010
        networks: 
            - potentiometer-network
        labels:
            - "SERVICE_5001_NAME=QuizEngine"
            - "SERVICE_TAGS=QuizEngineTag"
networks:
    potentiometer-network:
        name: potentiometer-network
        external: true