version: "3"
services:
    web:
        build: .
        ports:
            - "8080:5000"
        links:
            - db
        environment:
            SQLSERVER_HOST: "Server=db;Database=MyDatabase;User=SA;Password=aLQUIDa@9826;"
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433"
        environment:
            SA_PASSWORD: "aLQUIDa@9826"
            ACCEPT_EULA: "Y"