version: "3"
services:
    web:
        build: .
        links:
            - db
        environment:
            SQLSERVER_HOST: "Server=db;Database=MyDatabase;User=SA;Password=aLQUIDa@9826;"
        labels:
            - "SERVICE_5001_NAME=QuizEngine"
            - "SERVICE_TAGS=QuizEngineTag"
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433"
        environment:
            SA_PASSWORD: "aLQUIDa@9826"
            ACCEPT_EULA: "Y"